### ISSUE TITLE
如何在aarch64架构上编译项目

### ISSUE THREAD

**Issue by unmu** [pcg-mlp/KsanaLLM#10]
# 软硬件环境

使用docker container

* CANN: 7.0.RC1
* SOC_VERSION: ascend910b1
* python: 3.9.18
* OS: Ubuntu22.04
<img width="1128" alt="截屏2024-05-30 21 42 02" src="https://github.com/pcg-mlp/KsanaLLM/assets/58108391/225b5179-92b8-4b1b-8dbc-68c4c8e74975">

**Comment by xingjinglu** [comment]
> # 软硬件环境
> 使用docker container
> 
> * CANN: 7.0.RC1
> * SOC_VERSION: ascend910b1
> * python: 3.9.18
> * OS: Ubuntu22.04
> 
> <img alt="截屏2024-05-30 21 42 02" width="1128" src="https://private-user-images.githubusercontent.com/58108391/335202041-225b5179-92b8-4b1b-8dbc-68c4c8e74975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzkxODQsIm5iZiI6MTcxNzA3ODg4NCwicGF0aCI6Ii81ODEwODM5MS8zMzUyMDIwNDEtMjI1YjUxNzktOTJiOC00YjFiLThkYmMtNjhjNGM4ZTc0OTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTRhMDM0ZDQzYzZkMjgxZjFmNzZmZjIxY2NhZTQ1MWZiMmNmZTNkZDNiYWJkZTE1OWZiM2YwZjllNjI2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-5UgNU70Bg4O3ZzMbSTme1lK6Dql59m7moXVen9an0">

I think it is not support yet,  only ascend with x86 have been verified.
Maybe you can support this feature?
