### ISSUE TITLE
编译时 undefined reference  to `mha_varlen_fwd

### ISSUE THREAD

**Issue by lovelynight** [pcg-mlp/KsanaLLM#12]
环境信息：A100 cuda12.1 flash-attention2.5.7
编译报错如下

[100%] Built target runtime_test
/usr/bin/ld: [100%] Built target block_manager_test
../../../lib/libkernels.a(kernel_wrapper.cpp.o): in function `void ksana_llm::AttenVarlen<__nv_bfloat16>(void*, void*, void*, void*, llm_kernels::nvidia::RotaryEmbeddingCuda<__nv_bfloat16>&, int, int, int, int, int, int, int, int, bool, int, int, void**, void**, void*, std::optional<void*> const&, CUstream_st*)':
/mnt/data_disk/qihao.xjp/KsanaLLM/src/ksana_llm/kernels/nvidia/kernel_wrapper.cpp:190: undefined reference to `mha_varlen_fwd(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, c10::optional<at::Tensor>&, int, int, float, float, bool, bool, int, int, bool, c10::optional<at::Generator>)'
/usr/bin/ld: ../../../lib/libkernels.a(kernel_wrapper.cpp.o): in function `void ksana_llm::AttenVarlen<__half>(void*, void*, void*, void*, llm_kernels::nvidia::RotaryEmbeddingCuda<__half>&, int, int, int, int, int, int, int, int, bool, int, int, void**, void**, void*, std::optional<void*> const&, CUstream_st*)':
/mnt/data_disk/qihao.xjp/KsanaLLM/src/ksana_llm/kernels/nvidia/kernel_wrapper.cpp:190: undefined reference to `mha_varlen_fwd(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, c10::optional<at::Tensor>&, int, int, float, float, bool, bool, int, int, bool, c10::optional<at::Generator>)'
/usr/bin/ld: ../../../lib/libkernels.a(kernel_wrapper.cpp.o): in function `void ksana_llm::AttenVarlen<float>(void*, void*, void*, void*, llm_kernels::nvidia::RotaryEmbeddingCuda<float>&, int, int, int, int, int, int, int, int, bool, int, int, void**, void**, void*, std::optional<void*> const&, CUstream_st*)':
/mnt/data_disk/qihao.xjp/KsanaLLM/src/ksana_llm/kernels/nvidia/kernel_wrapper.cpp:190: undefined reference to `mha_varlen_fwd(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor>&, c10::optional<at::Tensor>&, int, int, float, float, bool, bool, int, int, bool, c10::optional<at::Generator>)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/ksana_llm/layers/CMakeFiles/layers_test.dir/build.make:155：bin/layers_test] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2297：src/ksana_llm/layers/CMakeFiles/layers_test.dir/all] 错误 2

请问如何解决？

**Comment by lovelynight** [comment]
执行的命令 cmake -DSM=80 -DWITH_TESTING=ON  ..
cmake的时候的信息如下
-- Found CUDA: /usr/local/cuda (found suitable version "12.1", minimum required is "11.8")
-- Determining NCCL version from /usr/include/nccl.h...
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
-- Running submodule update to fetch FlashAttention
-- FLAS_ATTN_PYTHON_SO: /usr/local/lib/python3.10/dist-packages/flash_attn-2.5.7-py3.10-linux-x86_64.egg/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so
-- using flash attention 2.5.7 from python
-- Running submodule build to fetch LLM_kernels
-- Found CUDA: /usr/local/cuda (found suitable version "12.1", minimum required is "11.2")
-- CUDA_VERSION 12.1 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDA_VERSION 12.1 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- Running submodule update to fetch cutlass
-- CMAKE_CUDA_FLAGS_RELEASE: -O3 -DNDEBUG --use_fast_math -Xcompiler -O3 -DCUDA_PTX_FP8_F2FP_ENABLED --use_fast_math
-- Assign GPU architecture (sm=80)
-- CMAKE_CUDA_FLAGS  -Xcompiler -Wall -ldl -g -DWMMA --expt-extended-lambda --expt-relaxed-constexpr --std=c++17 -DCUDA_PTX_FP8_F2FP_ENABLED -gencode arch=compute_80,code=sm_80
-- cutlass version is: 3.3.0

**Comment by whitelok** [comment]
可以试试cuda 11.8 + flashattention 2.5.6
