### ISSUE TITLE
【紧急】在910B上运行llama2-7b报错

### ISSUE THREAD

**Issue by zhaochaoxing** [pcg-mlp/KsanaLLM#13]
机器环境：x86_64 / 910B2C
cann和kernel版本：8.0.RC1.alpha003
gcc版本：11.2.0
报错信息：
RegisterAscendBinary aiv ret 107000
RegisterAscendBinary aiv ret 107000

[FATAL]  Acl return error KsanaLLM/3rdparty/LLM_kernels/csrc/kernels/ascend/attention/attention.cc:140, with ERROR 561103

[FATAL]  Acl return error KsanaLLM/3rdparty/LLM_kernels/csrc/kernels/ascend/attention/attention.cc:146, with ERROR 161001

![image](https://github.com/pcg-mlp/KsanaLLM/assets/109726331/29dab46b-92b7-42c1-8950-3e3d8abd7275)

感觉可能是代码和cann版本兼容性问题，麻烦给一个适配的cann版本。
在910B上，pytorch使用cpu版本？还是ascend_npu版本？
麻烦解答一下，感谢

**Comment by pcg-mlp** [comment]
机器环境：x86_64 / 910B2C
cann：7.0.0
gcc版本：9.4.0

**Comment by whitelok** [comment]
pytorch使用ascend_npu版本

**Comment by whitelok** [comment]
是demo中的llama7B模型吗？

**Comment by zhaochaoxing** [comment]
> 是demo中的llama7B模型吗？

是的，跑的demo里的llama2-7b。server启动报错：
RegisterAscendBinary aiv ret 107000
RegisterAscendBinary aiv ret 107000
![image](https://github.com/pcg-mlp/KsanaLLM/assets/109726331/5e1de85e-e85b-4648-91ee-9fcbaebd9b5e)
发请求则attention算子报错。

**Comment by whitelok** [comment]
seems good under my environment 
<img width="1704" alt="截屏2024-05-31 19 18 54" src="https://github.com/pcg-mlp/KsanaLLM/assets/1612381/b550d30a-be8c-4c65-a469-93f6afb42f97">

**Comment by pcg-mlp** [comment]
目前华为的环境标准化还不足，相关底层库的依赖关系比较trick。所以暂时只在腾讯内部环境有充分的验证。
我们正在优化华为的实现，并准备华为云上标准机型的镜像。
预期6月底能够支持上。

**Comment by zhaochaoxing** [comment]
没有镜像环境问题确实不确定性太大，我期待6月底能够使用。另外KsanaLLM在910B上有没有性能测试数据？可否透露一些？

**Comment by pcg-mlp** [comment]
现在的性能还算不上优秀，我们希望能在2个月内达到和A100上相同的性能
