### ISSUE TITLE
ksanallm complile error

### ISSUE THREAD

**Issue by chenpinganan** [pcg-mlp/KsanaLLM#17]
cmd： cmake -DSM=80 -DWITH_TESTING=ON .. && make -j32

/KsanaLLM/src/ksana_llm/kernels/nvidia/kernel_wrapper.cpp:206:21: error: ‘mha_varlen_fwd’ was not declared in this scope
  206 |       mha_varlen_fwd(q_tmp_tensor, torch::reshape(k_tensor, {total_tokens, num_kv_heads, head_size}),
      |       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  207 |                      torch::reshape(tt[2], {total_tokens, num_kv_heads, head_size}), out_tensor,
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  208 |                      seqlen_tensor.to(torch::kInt32), seqlen_tensor.to(torch::kInt32), seqused_k, alibi_slopes_tensor,
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  209 |                      max_tokens, max_tokens, 0.f, 1.0 / sqrt(head_size), false, is_causal, -1, -1, false, c10::nullopt);

**Comment by whitelok** [comment]
please provide flash_attn version
