### ISSUE TITLE
有计划支持多模态大模型吗？

### ISSUE THREAD

**Issue by sfyumi** [pcg-mlp/KsanaLLM#18]
比如 [MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V)

**Comment by pcg-mlp** [comment]
一念目前对多模态模型的支持方式是作为多模态模型的一个环节来使用。
按照[Efficient Multimodal Large Language Models:A Survey](https://arxiv.org/pdf/2405.10739) 中figure3的结构，由用户自行调用多模态encoder生成visual token，然后textual token拼接后调用一念。
另外，一念还提供token embedding输出拼接的能力。多模态encoder生成embedding后，与一念text token输出embedding拼接在一起。如下图所示
<img width="425" alt="多模态embedding拼接" src="https://github.com/user-attachments/assets/d1a72db7-7c9f-40f8-86f8-0e69f9d4f11f">

**Comment by sfyumi** [comment]
多谢
