### ISSUE TITLE
你好，请问有计划支持aarch64架构上的910B吗

### ISSUE THREAD

**Issue by yanzhuo77** [pcg-mlp/KsanaLLM#22]
如题，感谢

**Comment by pcg-mlp** [comment]
这块会支持的，目前正在和华为合作优化现有机型的性能。

**Comment by yanzhuo77** [comment]
> 这块会支持的，目前正在和华为合作优化现有机型的性能。

可以基于现有算子发布一个aarch64版本吗，比直接运行python快就行
