### ISSUE TITLE
支持 fp8 量化

### ISSUE THREAD

**Issue by sfyumi** [pcg-mlp/KsanaLLM#27]
vLLM 和 tensorrt llm 都支持 fp8 量化了。而且从实践上看，fp8 量化相对 int8 量化，不管是性能还是模型效果上都有优势。
一念 LLM 有对 fp8 量化支持的规划吗？

**Comment by pcg-mlp** [comment]
fp8量化已经支持。
通过修改yaml文件即可开启fp8量化
https://github.com/pcg-mlp/KsanaLLM/blob/main/examples/ksana_llm.yaml#L60  修改dtype为fp8_e5m2, fp8_e4m3可使用kv_cache fp8；
https://github.com/pcg-mlp/KsanaLLM/blob/main/examples/ksana_llm.yaml#L65  修改 quant_method为fp8_e4m3可开启matmul fp8

**Comment by sfyumi** [comment]
这种支持的是静态 scale 还是动态 scale 啊？
支持 [AutoFP8](https://github.com/neuralmagic/AutoFP8) 生成的大模型 fp8 权重吗？

**Comment by pcg-mlp** [comment]
相关支持已经开发，正在CR中
