### ISSUE TITLE
Support for Qwen-v1.5-110b

### ISSUE THREAD

**Issue by Superskyyy** [pcg-mlp/KsanaLLM#4]
Hi, does KsanaLLM currently support Qwen-v1.5-110b? If not is it possible to adapt the framework to do so? Thanks!

**Comment by pcg-mlp** [comment]
Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.

**Comment by Superskyyy** [comment]
> Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.

We are very interested in adopting KsanaLLM for larger models. Thanks for the update!

**Comment by xingjinglu** [comment]
> > Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.
> 
> We are very interested in adopting KsanaLLM for larger models. Thanks for the update!

The verification is finished. KsanaLLM can run Qwen-v1.5-110b on 8*A100 GPUs with 40GB memory.

**Comment by Superskyyy** [comment]
> > > Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.
> 
> > 
> 
> > We are very interested in adopting KsanaLLM for larger models. Thanks for the update!
> 
> 
> 
> The verification is finished. KsanaLLM can run Qwen-v1.5-110b on 8*A100 GPUs.

I assume it also runs on 8 Ascend NPUs?

**Comment by whitelok** [comment]
> > > > Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.
> > 
> > 
> > > 
> > 
> > 
> > > We are very interested in adopting KsanaLLM for larger models. Thanks for the update!
> > 
> > 
> > The verification is finished. KsanaLLM can run Qwen-v1.5-110b on 8*A100 GPUs.
> 
> I assume it also runs on 8 Ascend NPUs?

not support. only support one NPU now.  multiple npu scheduled in June/July.

**Comment by Superskyyy** [comment]
> > > > > Qwen-v1.5-110b is not verified on KsanaLLM right now. We will check this and reply later.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > We are very interested in adopting KsanaLLM for larger models. Thanks for the update!
> > > 
> > > 
> > > The verification is finished. KsanaLLM can run Qwen-v1.5-110b on 8*A100 GPUs.
> > 
> > 
> > I assume it also runs on 8 Ascend NPUs?
> 
> not support. only support one NPU now. multiple npu scheduled in June/July.

Thanks!
