### ISSUE TITLE
No module named 'libtorch_serving'

### ISSUE THREAD

**Issue by LiweiPE** [pcg-mlp/KsanaLLM#5]
After installed buy cmake I got this error. What is the reason and how to fix it?
![image](https://github.com/pcg-mlp/KsanaLLM/assets/48242387/56c09c53-d669-45dc-84d6-6a90d633b50d)

**Comment by xingjinglu** [comment]
libtorch_serving.so 在你build的路径下面，例如 KsanaLLM/build/lib

需要将该路径设置在PYTHONPATH环境变量里，
`export PYTHONPATH=/yourpath/KsanaLLM/build/lib:$PYTHONPATH`

**Comment by LiweiPE** [comment]
Thanks for the answer, I installed by distribute method and I got this error now:
![image](https://github.com/pcg-mlp/KsanaLLM/assets/48242387/ed307aed-7677-45ae-8100-cbe666db93b9)

**Comment by xingjinglu** [comment]
I have not re-produce your error now.

For investigating this problem, **please paste the error log here and give a description of your envritonment**.

BTW, you build KsanaLLM with the nvidia image?

And give my  environment for reference.
CUDA: 11.8
Driver:  525.116.04
GPU: A10

**Comment by LiweiPE** [comment]
With nvidia image there is no error for installation. These errors come from conda environment installation. Final question, do you plan to support GPTQ quantization models in this framework? This issue can be closed, thanks.

**Comment by pcg-mlp** [comment]
GPTQ may be supported in Q3/Q4 2024. 
Scheduling performance and Ascend kernel optimization are in first priority right now
