### ISSUE TITLE
在A100上跑qwen1.5-72B-chat-tp4会卡住

### ISSUE THREAD

**Issue by mjp9527** [pcg-mlp/KsanaLLM#6]
配置yaml:
# 全局设置
setting:
  # 全局配置
  global:
    # TP并行
    tensor_para_size: 4
    # PP并行
    pipeline_para_size: 1
    # 是否启用lora适配，false表示不启用，true表示启用
    enable_lora_adapter: false
    # 运行设备：英伟达GPU or 华为昇腾NPU，默认是GPU
    device: gpu
  # 调度相关配置
  batch_scheduler:
    # 请求在队列中的超时时间，单位为毫秒
    waiting_timeout_in_ms: 3600000
    # 请求队列的最大等待长度，超过对应长度时会丢弃新请求，主要用于流控。
    max_waiting_queue_len: 1200
    # 一个调度step处理的最大token个数，一次context decode视为多个token。
    max_step_tokens: 4096
    # 每一步推理时的最大batch_size
    max_batch_size: 256
    # 最大输入输出长度之和, 相当于prompt_len+max_new_tokens
    max_token_len: 2048
    # 单个请求可用blck小于该值触发换出
    swapout_block_threshold: 1.0
    # 单个请求可用block大于该值触发换入
    swapin_block_threshold: 2.0
    # 单个请求可用block大于该值拉起新任务
    launch_block_threshold: 2.0
    # 用于执行异步swap的线程池大小
    swap_threadpool_size: 8
    # prefix缓存token数，0表示不缓存，-1表示自动适配(未实现)
    prefix_cache_len: 0
  # 显存块相关配置
  block_manager:
    # 单个block可处理的最大token个数
    block_token_num: 16
    # 保留的显存占比，单位为百分比。
    reserved_device_memory_ratio: 0.1
    # Lora权重的显存占比
    lora_deivce_memory_ratio: 0.0
    # Lora权重在host上的预分配大小，相比device上的倍数
    lora_host_memory_factor: 10.0
    # block部分的显存占比，<0表示使用所有剩余显存
    block_device_memory_ratio: -1.0
    # block部分在host上的预分配大小，相比device上的倍数
    block_host_memory_factor: 2.0
    prefix_cache_len: 0
  # 性能统计相关配置
  profiler:
    # 统计周期，每隔多少秒输出一次统计数据
    stat_interval_second: 5
    # 缓存队列大小
    stat_buffer_size: 1024
    # 异步上报的线程池大小
    report_threadpool_size: 4
# 模型配置
model_spec:
  # 基础模型配置，只能有一个
  base_model:
    # 模型路径
    model_dir: Qwen_Qwen1.5-72B-Chat/

看占用是两个卡100%占用，两个卡为0%，感觉是卡住NCCL通信上了

**Comment by pcg-mlp** [comment]
我们复现一下

**Comment by mjp9527** [comment]
请问有结果吗

**Comment by xingjinglu** [comment]
> 请问有结果吗

内部做了验证，没有发现问题
测试环境：A100-40GB * 4
代码commit id： 9201ca09f510244b3fa62b7360c0930508936995

**Comment by mjp9527** [comment]
> > 请问有结果吗
> 
> 内部做了验证，没有发现问题，服务配置跟你贴出来的是一致的。 测试环境：A100-40GB * 4 代码commit id： `9201ca09f510244b3fa62b7360c0930508936995`
> 
> 你在试一下？如果有详细的log，也可以贴出来看看

设置了 NLLM_LOG_LEVEL=DEBUG ，但是没有任何输出，感觉还没走到处理阶段：
<img width="472" alt="image" src="https://github.com/pcg-mlp/KsanaLLM/assets/54735487/96314b13-9445-4d8f-b947-fdc5e09422a8">
服务可以启动，跑serving_client时卡主了，Qwen加载太慢，我用2卡llama2-7b也测了下，和qwen现象一样，一个卡占用100%，一个卡0%，感觉像卡在NCCL通信上
<img width="383" alt="image" src="https://github.com/pcg-mlp/KsanaLLM/assets/54735487/35a619ad-ec32-4172-b829-1c03f61d1768">
